spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo6
    username: root
    password: root44395222
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
